// this file is generated by `deno run create-day <year> <day>`
import type { Day } from "../Day.ts";

import * as day_01 from "./day_01.ts";
import * as day_02 from "./day_02.ts";
import * as day_03 from "./day_03.ts";

export const days: Day[] = [
    day_01,
    day_02,
    day_03
];
