// get year and day from args
const [year, day] = Deno.args;

if (!year || !day) {
  console.error("Usage: create-day <year> <day>");
  Deno.exit(1);
}

const template = await Deno.readFile("./src/day-template.ts");
await Deno.writeFile(`./src/year_${year}/day_${day}.ts`, template);

const days = [];
for await (const dirEntry of Deno.readDir(`./src/year_${year}`)) {
  if (dirEntry.name.startsWith("day_")) {
    days.push(dirEntry.name.split(".")[0]);
  }
}
days.sort();

console.log(days);
const index = `// this file is generated by \`deno run create-day <year> <day>\`
import type { Day } from "../Day.ts";

${
  days.map((day) => `import * as ${day} from "./${day}.ts";`)
    .join("\n")
}

export const days: Day[] = [
  ${days.map((day) => `${day}`).join(",\n    ")}
];
`;

await Deno.writeTextFile(`./src/year_${year}/index.ts`, index);
